-- AlterTable
ALTER TABLE `strategy_binary` ADD COLUMN `hier` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `level` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `ref` VARCHAR(191) NOT NULL DEFAULT '';
