/*
  Warnings:

  - The primary key for the `balance` table will be changed. If it partially fails, the table could be left without primary key constraint.

*/
-- AlterTable
ALTER TABLE `balance` DROP PRIMARY KEY,
    MODIFY `wallet` ENUM('MAIN', 'PENDING', 'WITHDRAW', 'GENERAL_POINT', 'BINARY_CEILING_USER', 'BINARY_LEFT_POINT', 'BINARY_RIGHT_POINT', 'BINARY_LEFT_POINT_NEW', 'BINARY_RIGHT_POINT_NEW', 'BINARY_LEFT_POINT_PAY', 'BINARY_LEFT_POINT_TOTAL', 'BINARY_RIGHT_POINT_PAY', 'BINARY_RIGHT_POINT_TOTAL', 'DIRECT_BONUS', 'WINWIN_BONUS', 'TOKENWAY_BONUS', 'TOKENTEEN_BONUS', 'TOKENONE_BONUS', 'BINARY_BONUS') NOT NULL DEFAULT 'MAIN',
    ADD PRIMARY KEY (`user_id`, `wallet`);

-- AlterTable
ALTER TABLE `balance_history` MODIFY `wallet` ENUM('MAIN', 'PENDING', 'WITHDRAW', 'GENERAL_POINT', 'BINARY_CEILING_USER', 'BINARY_LEFT_POINT', 'BINARY_RIGHT_POINT', 'BINARY_LEFT_POINT_NEW', 'BINARY_RIGHT_POINT_NEW', 'BINARY_LEFT_POINT_PAY', 'BINARY_LEFT_POINT_TOTAL', 'BINARY_RIGHT_POINT_PAY', 'BINARY_RIGHT_POINT_TOTAL', 'DIRECT_BONUS', 'WINWIN_BONUS', 'TOKENWAY_BONUS', 'TOKENTEEN_BONUS', 'TOKENONE_BONUS', 'BINARY_BONUS') NOT NULL DEFAULT 'MAIN';
